[project]
name = "MNIST"
version = "0.1.0"
requires-python = ">=3.14.0"
dependencies = [
  "matplotlib>=3.11.1",
  "pandas>=3.0.5",
  "torch>=2.11.0",
  "torchvision>=0.26.0",
  "triton-rocm>=3.6.0 ; sys_platform == 'linux'",
]

[tool.uv.sources]
torch = [
  { index = "pytorch-rocm", marker = "sys_platform == 'linux'" },
]
torchvision = [
  { index = "pytorch-rocm", marker = "sys_platform == 'linux'" },
]
triton-rocm = [
  { index = "pytorch-rocm", marker = "sys_platform == 'linux'" },
]

[[tool.uv.index]]
name = "pytorch-rocm"
url = "https://download.pytorch.org/whl/rocm7.2"
explicit = true
